name: Tests

# Cu치ndo ejecutar: cuando haces push o pull request
on:
  push:
    branches: main
  pull_request:
    branches: main

# El trabajo que va a hacer
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Descargar mi c칩digo
    - uses: actions/checkout@v4
    
    # 2. Instalar Java
    - uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
    
    # 3. Ejecutar mis tests
    - name: Ejecutar tests
      run: |
        chmod +x .github/scripts/run_tests.sh
        ./.github/scripts/run_tests.sh
    
    # 4. Generar badge din치mico con el total de tests
    - name: Generate tests badge
      run: |
        # Crear el badge usando Shields.io din치mico
        BADGE_URL="https://img.shields.io/badge/tests-${{ env.total_tests }}-ejecutados-blue"
        echo "BADGE_URL=$BADGE_URL" >> $GITHUB_ENV
      shell: bash